version: '3'

services: 
  nextcloud:
    image: 'nextcloud:16'
    container_name: 'nextcloud'
    environment: 
      - 'SQLITE_DATABASE=nextcloud'
      - 'NEXTCLOUD_ADMIN_USER=nc_admin_user'
      - 'NEXTCLOUD_ADMIN_PASSWORD=nc_admin_password'
      - 'NEXTCLOUD_TRUSTED_DOMAINS=nextcloud'
    networks: 
      - 'nc_network'
    ports:
      - '8080:80'

networks: 
  nc_network:
    external: true